---
title: "ST2195 Programming for Data Science"
author: "Lee Hin Sing Raymond"
date: "February 2022"
output: pdf_document
---

# Practice Assignment 7

### Introduction

This is the seventh assignment for the course [**ST2195 Programming for Data Science**](https://www.lse.ac.uk/study-at-lse/uolip/Assets/documents/21-22-CIS-Sheets/ST2195-Programming-for-data-science.pdf). R and Python programming will be the main focus of this introductory course.

This is a compulsory 200-course for students who are going for a **BSc Data Science and Business Analytics** degree in the University of London, the academic direction of the degree program is provided by [London School of Economics and Political Science](https://www.lse.ac.uk/) (LSE). The course convenors are Mr [Ioannis Kosmidis](https://www.ikosmidis.com/) and Dr [Kostas Kalogeropoulos](https://www.lse.ac.uk/Statistics/People/Dr-Kostas-Kalogeropoulos).

Throughout the half-year course, there will be a take-home assignment every two weeks to demonstrate what we have learned before. All final works should be uploaded to a GitHub repository for version control.

### Assignment

Download the titanic dataset from [kaggle](https://www.kaggle.com/competitions/titanic).
Unzip the folder and keep only the train.csv file. Rename the file as titanic.csv.

Create a GitHub repository called “st2195_assignment_7” and include an R script able to perform the operations described below.

* Generate a series of bar charts to describe the gender, ticket class and survival of the passengers onboard. [1 point]

* Generate a histogram for the passengers’ age. Furthermore, describe the passengers’ age using the following two boxplots: age per ticket class and age based on survival. [1 point]

* Generate a histogram for the travel fare and a table showing the number of people who did not pay – you may want to check on Google why a handful of people was on board for free! [1 points]

* A chart of your choice to describe the family size per ticket class [1.5 points]

* A series of stacked bar charts to show the how survival differs for different gender and ticket class [1.5 points]

* A violin chart describing how survival related to age and gender [1.5 points]

* A violin chart describing the survival rate related to age and ticket class [1.5 points]

* From the graphs above, what kind of associations between the variables like age, gender, ticket class and the survival do you observe? [1 point]

Note: it would be best to use ggplot.